version: "3.8"

services:
  backend:
    container_name: pdf_chat_backend
    image: pdf_chat/backend
    build:
      context: ./pdf-chat-be
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8086:8086"
    networks:
      - chat_network
    depends_on:
      - db

  frontend:
    container_name: pdf_chat_frontend
    image: pdf_chat/frontend
    build:
      context: ./pdf-chat-ui
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./configs:/etc/nginx/conf.d
    networks:
      - chat_network

  db:
    image: mongo:latest
    container_name: pdf_chat_db
    restart: always
    ports:
      - "27018:27017"
    networks:
      - chat_network
    volumes:
      - pdf-chat-mongo-data:/data/db

  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] # Enable GPU support
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - chat_network

volumes:
  pdf-chat-mongo-data:
    external: true
  ollama:
    external: true

networks:
  chat_network:
    external: true
